error: use new gjs API to detect cancellations
Instead of matching on the error string, now that this is supported in
GJS.

https://bugzilla.gnome.org/show_bug.cgi?id=671169